[package]
name = "try-audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#clap = "3.2.6"
anyhow = "1.0.58"
cpal = "0.14.1"

