[package]
name = "try-audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.5"
#clap = "3.2.6"
anyhow = "1.0.58"

